language: objective-c
osx_image: xcode8
env:
  - PLATFORM="ios" SCHEME="FisherHallClientTests" DESTINATION="iOS Simulator,name=iPhone 7,OS=10.0"
before_script:
  - carthage bootstrap --platform $PLATFORM --no-use-binaries
  -  xcodebuild -project FisherHallClient.xcodeproj -list
script:
  - xcodebuild -project FisherHallClient.xcodeproj -scheme $SCHEME -destination "$DESTINATION" build test
